apiVersion: 1
kind: PersistentVolumeClaim
metadata:
  name: pvc-1
spec:
  #O bind e feito pela definicao de igualdade
  #O mesmo modo de acesso
  accessMode:
    - ReadWriteOnce
  # A mesma capacidade
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard