apiVersion: v1
kind: Pod
metadata:
  name: db-noticias
  #Para definir um servico vou definir uma label
  labels:
    app: db-noticias
spec:
  containers:
    - name: db-noticias-container
      image: aluracursos/mysql-db:1
      #Portas do container
      ports:
        - containerPort: 3306
      #Importa todo o configmap de acordo com o name
      envFrom:
        - configMapRef:
            name: db-configmap