apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx-deployment
spec:
  replicas: 3
  template:
      metadata:
        name: nginx-pod
        labels:
          app: nginx-pod
      spec:
        containers:
            - name: nginx-container
            #Aqui eu consigo colocar a versao que eu quero
            #No caso do versionamento com o deployment
            #image: nginx:2
            #image: nginx:1
              image: nginx:stable
              ports:
                - containerPort: 80
  selector:
      matchLabels:
          app: nginx-pod