apiVersion: apps/v1
kind: Deployment
##########################################
#Esta parte eu posso copiar do arquivo pod
##########################################
metadata:
  name: portal-noticias-deployment
spec:
#Definimos um template padrao
#Aqui vai as informacoes do nosso pod
  template: #Dados do pod que sera gerenciado
    metadata: #referente ao pod
      name: portal-noticias
      #Para definir um servico vou definir uma label
      labels:
        app: portal-noticias
    spec:
      containers:
        - name: portal-noticias-container
          image: aluracursos/portal-noticias:1
          #Portas do container
          ports:
            - containerPort: 80
          envFrom: #Importa o configmap para o Pod
            - configMapRef:
                name: portal-configmap
          #Definind prova de vida da aplicacao
          livenessProbe:
            httpGet:
              #caminho da rota localhost:30000/
              path: /
              #Porta em que o container esta respondendo a aplicacao
              port: 80
              #Em quanto tempo o teste deve ser feito
            periodSeconds: 10
            #n maximo de falhas para erros no container
            failureThreshold: 3
            #Em quanto tempo o container deve executar o primeiro teste apos subir
            initialDelaySeconds: 20
                    #Caso nao consiga executar na 4 vez ele enviara as requisicoes ignorando o readnessprobe
          readinessProbe: 
            httpGet:
              path: /
              port: 80
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 20
            #Cada pod que tenha um container
          resources:
          #10 milicores foi o recurso definido
            cpu: 10m
##########################################
#        FIM DA COPIA                    #
##########################################
#Devemos definir o numero de replicas
#Por padrao o numero e 1
  replicas: 3
  #precisamos informar os recursos que tenham match labels
  selector:
    matchLabels:
      app: portal-noticias