apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  #Label para definir a comunicacao com o servico
  labels:
  #Chave valor definido no servico
    app: primeiro-pod
spec:
  containers:
    - name: container-pod-1
      image: nginx:latest
      ports:
        - containerPort: 80