apiVersion: v1
kind: Service
metadata:
  name: svc-pod-2
spec:
#Tipo desse servico sera um ClusterIP diferente do primeiro servico que sera um NodePort
  type: ClusterIP
  selector:
    app: segundo-pod
  ports:
    - port: 9000 #Porta de comunicacao do servico
      targetPort: 80 #Porta interna