apiVersion: v1
kind: Service
metadata:
  name: svc-pod-1
spec:
  #Estou criando um nodeport que ira se
  #comunicar com o servico svc-pod-2.yaml
  type: NodePort
  ports:
    - port: 80 #assim ambas as portas de comunicacao e interna serao as mesmas
      #targetPort: 8080
      #Posso definir uma porta para o no default
      #No range
      #nodeport: 30000-32777
      nodePort: 30000
  selector: #chave definida no arquivo do pod
    app: primeiro-pod