apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sistema-noticias-statefulset
spec:
  replicas: 1
  #Informacoes do POD que sera criado dentro do statefulset
  template:
    metadata:
      labels:
        app: sistema-noticias
      name: sistema-noticias
      #Definicao das especificacoes do pod
    spec:
      containers:
        - name: sistema-noticias-container
          image: aluracursos/sistema-noticias:1
      
        #Portas do container
          ports:
            - containerPort: 80
          envFrom: #Importa o configmap para o Pod
            - configMapRef:
                name: sistema-configmap
          volumeMounts:
            - name: imagens
              mountPath: /var/www/uploads #Este e o caminho visualizado dentro do exec
            - name: sessao
              mountPath: /tmp
      #Precisamos definir o volume no container
      volumes:
        - name: imagens
          persistentVolumeClaim:
            claimName:  imagens-pvc
        - name: sessao
          persistentVolumeClaim:
            claimName:  sessao-pvc
  #Seletor do arquivo Deployment que criamos
  selector:
    matchLabels:
      app: sistema-noticias
  #SVC definido para gerenciar o pod
  serviceName: svc-sistema-noticias