apiVersion: v1
kind: Pod
metadata:
  name: db-noticias
  #Para definir um servico vou definir uma label
  labels:
    app: db-noticias
spec:
  containers:
    - name: db-noticias-container
      image: aluracursos/mysql-db:1
      #Portas do container
      ports:
        - containerPort: 3306
      #Variaveis de ambiente:
      env:
        - name: "MYSQL_ROOT_PASSWORD"
          value: "qlw2e3r4"
        - name: "MYSQL_DATABASE"
          value: "empresa"
        - name: "MYSQL_PASSWORD"
          value: "qlw2e3r4"