apiVersion: v1
kind: ConfigMap
metadata:
  name: sistema-configmap
data:
#Chave : Valor
#No caso do host eu defini o nome resolvido pelo DNS mas pode ser o ip tambem
  HOST_DB: svc-db-noticias:3306
  USER_DB: root
  PASS_DB: q1w2e3r4
  DATABASE_DB: empresa
