apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: portal-noticias-replicaset
spec:
#Definimos um template padrao
#Aqui vai as informacoes do nosso pod
  template: #Dados do pod que sera gerenciado
    metadata: #referente ao pod
      name: portal-noticias
      #Para definir um servico vou definir uma label
      labels:
        app: portal-noticias
    spec:
      containers:
        - name: portal-noticias-container
          image: aluracursos/portal-noticias:1
          #Portas do container
          ports:
            - containerPort: 80
          envFrom: #Importa o configmap para o Pod
            - configMapRef:
                name: portal-configmap
#Devemos definir o numero de replicas
#Por padrao o numero e 1
  replicas: 3
  #precisamos informar os recursos que tenham match labels
  selector:
    matchLabels:
      app: portal-noticias